module.exports.Reset = '\x1b[0m'
module.exports.Bright = '\x1b[1m'
module.exports.Dim = '\x1b[2m'
module.exports.Underscore = '\x1b[4m'
module.exports.Blink = '\x1b[5m'
module.exports.Reverse = '\x1b[7m'
module.exports.Hidden = '\x1b[8m'

module.exports.Black = '\x1b[30m'
module.exports.Red = '\x1b[31m'
module.exports.Green = '\x1b[32m'
module.exports.Yellow = '\x1b[33m'
module.exports.Blue = '\x1b[34m'
module.exports.Magenta = '\x1b[35m'
module.exports.Cyan = '\x1b[36m'
module.exports.White = '\x1b[37m'
module.exports.Gray = '\x1b[90m'

module.exports.BgBlack = '\x1b[40m'
module.exports.BgRed = '\x1b[41m'
module.exports.BgGreen = '\x1b[42m'
module.exports.BgYellow = '\x1b[43m'
module.exports.BgBlue = '\x1b[44m'
module.exports.BgMagenta = '\x1b[45m'
module.exports.BgCyan = '\x1b[46m'
module.exports.BgWhite = '\x1b[47m'
