module.exports.ping = require('./ping')
module.exports.help = require('./help')
module.exports.shardinfo = require('./shardinfo')
module.exports.prefix = require('./prefix')
module.exports.mail = require('./mail')
module.exports.cooldown = require('./cooldown')
module.exports.register = require('./register')
